[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[dev]
  port = 8888

[[edge_functions]]
  function = "mcp"
  path = "/mcp"

[[edge_functions]]
  function = "mcp"
  path = "/.well-known/oauth-authorization-server"

[[edge_functions]]
  function = "mcp"
  path = "/auth"

[[edge_functions]]
  function = "mcp"
  path = "/token"

[[edge_functions]]
  function = "mcp"
  path = "/register"