[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[dev]
  port = 8888

[[edge_functions]]
  function = "mcp-simple"
  path = "/mcp"

[[edge_functions]]
  function = "hello"
  path = "/hello"

# Subdomain redirect for mcp.penguinbank.cloud
[[redirects]]
  from = "https://mcp.penguinbank.cloud/*"
  to = "https://penguinbank.cloud/mcp"
  status = 200
  force = true

[[redirects]]
  from = "http://mcp.penguinbank.cloud/*"
  to = "https://penguinbank.cloud/mcp"
  status = 301
  force = true