[build]
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[edge_functions]]
  function = "mcp"
  path = "/mcp/*"

[dev]
  port = 8888

[[headers]]
  for = "/mcp/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"