// This file is auto-generated by Supabase CLI
// Run 'npm run db:types' to regenerate

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      accounts: {
        Row: {
          id: string
          user_id: string
          account_type: string
          account_number: string
          balance: number
          available_balance: number
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          account_type: string
          account_number: string
          balance?: number
          available_balance?: number
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          account_type?: string
          account_number?: string
          balance?: number
          available_balance?: number
          created_at?: string
        }
      }
      bills: {
        Row: {
          id: string
          user_id: string
          payee: string
          statement_balance: number
          minimum_payment: number
          due_date: string
          is_paid: boolean
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          payee: string
          statement_balance: number
          minimum_payment: number
          due_date: string
          is_paid?: boolean
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          payee?: string
          statement_balance?: number
          minimum_payment?: number
          due_date?: string
          is_paid?: boolean
          created_at?: string
        }
      }
      payment_history: {
        Row: {
          id: string
          bill_id: string
          account_id: string
          amount: number
          payment_type: string
          confirmation_number: string
          created_at: string
        }
        Insert: {
          id?: string
          bill_id: string
          account_id: string
          amount: number
          payment_type: string
          confirmation_number: string
          created_at?: string
        }
        Update: {
          id?: string
          bill_id?: string
          account_id?: string
          amount?: number
          payment_type?: string
          confirmation_number?: string
          created_at?: string
        }
      }
      transactions: {
        Row: {
          id: string
          account_id: string
          transaction_type: string
          amount: number
          merchant: string | null
          category: string | null
          description: string | null
          balance_after: number | null
          created_at: string
        }
        Insert: {
          id?: string
          account_id: string
          transaction_type: string
          amount: number
          merchant?: string | null
          category?: string | null
          description?: string | null
          balance_after?: number | null
          created_at?: string
        }
        Update: {
          id?: string
          account_id?: string
          transaction_type?: string
          amount?: number
          merchant?: string | null
          category?: string | null
          description?: string | null
          balance_after?: number | null
          created_at?: string
        }
      }
      users: {
        Row: {
          id: string
          email: string
          name: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          email: string
          name: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string
          created_at?: string
          updated_at?: string
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}